version: "2.4"
services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    #mem_limit: 10G
    volumes:
      - ./minecraft-sync/config:/config
      - ./minecraft-sync/mods:/mods
      - ./mods.txt:/extras/mods.txt
      - ./minecraft-data:/data
    environment:
      #- UID=1000
      #- GID=1000

      - EULA=true
      - MEMORY=13G

      - VERSION=1.19.2
      - TYPE=fabric
      - FABRIC_LOADER_VERSION=0.14.24
      - PACKWIZ_URL=http://172.17.0.1/packwiz/dragon-home-mod-pack/pack.toml
      - MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES=false
      - MODRINTH_ALLOWED_VERSION_TYPE=beta
      - MODRINTH_PROJECTS=owo-lib,gotta-go-fast-fabric,dynmap,chunky,vanish,styled-chat,styledplayerlist,styled-nicknames,spark,banhammer,luckperms,ledger,invview,essential-commands,easyauth
      - MODS_FILE=/extras/mods.txt

      - REPLACE_ENV_VARIABLE_PREFIX=MCCFG_
      - MCCFG_SIMPLEVOICECHAT_VOICE_HOST=

      # server.properties
      - ENFORCE_SECURE_PROFILE=false
      - ONLINE_MODE=false
      - SYNC_CHUNK_WRITES=false
      - ENABLE_COMMAND_BLOCKS=true
      - "MOTD=\\u00a7c\\u2593\\u2593\\u00a76\\u2592\\u2592\\u00a7e\\u2591\\u2591\\u00a7b Dragon Home\\u00a7e \\u2591\\u2591\\u00a76\\u2592\\u2592\\u00a7c\\u2593\\u2593\n\\u2593\\u2593\\u00a76\\u2592\\u2592\\u00a7e\\u2591 cozy tech magic \\u2591\\u00a76\\u2592\\u2592\\u00a7c\\u2593\\u2593"
      - DIFFICULTY=normal
      - SPAWN_PROTECTION=0
      #- ENABLE_WHITELIST=true
      #- "SEED=0"

    ports:
      - "25565:25565"
      - "24454:24454/udp" # SimpleVoiceChat
      - "8123:8123" # Dynmap

